### PR TITLE
e.jsEvaluationValue is undefined

### PR DESCRIPTION
**Pull request by dima11221122**
### Environment

- react@15.4.2
- react-native@0.41.2
- Android 6.0

In my application your package didn't work. When i debugged, i found that param `e.jsEvaluationValue` was `null` in method `_updateWebViewHeight`, maybe because react-native has [bug](https://github.com/facebook/react-native/issues/7788).

## Solution
I rewrote the communication between app and webView on postMessage/onMessage. I had problem with a notify through postMessage, but [this comment](https://github.com/facebook/react-native/issues/11594#issuecomment-281232273) helped me. Maybe you known better solution for it.

### CODE REVIEW

**Comment by scazzy** [comment]
thanks for raising @dima11221122 . Will test your PR

**Comment by UrbanSam** [comment]
It works fine in android ! Even on android 4.4.4.
However in IOS, the height often way too long and creating empty space at bottom.

## Solution
One way to fix this was change `waitForBridge()` to `setTimeout(waitForBridge, 200)`
And add a defaultHeight in defaultProps to some value much smaller than what your content is.

**Comment by dima11221122** [comment]
Thanks @UrbanSam for testing on iOS. If i will set height in defaultProps and change `waitForBridge()` on `setTimeout(waitForBridge, 200)`, then will this enough? Will it work on iOS?

**Comment by UrbanSam** [comment]
@dima11221122 Yup at least it works on my simulator. Will let you know if it works in actual device.

**Comment by UrbanSam** [comment]
@dima11221122 Yup it works fine on my Iphone 5s.

**Comment by dima11221122** [comment]
I haven't forgotten about PR!) Now i'm busy, i fixed later

**Pull request merged**
